/**
 * User ROLES
 * */
export enum UserRole {
  USER = 'User',
  MOD = 'Mod',
  ADMIN = 'Admin',
}

export const REGISTRATION_ERROR = {
  MISSING_MANDATORY_PARAMETERS: 'REGISTRATION.MISSING_MANDATORY_PARAMETERS',
  PASSWORD_TOO_WEAK: 'REGISTRATION.PASSWORD_TOO_WEAK',
  EMAIL_ALREADY_REGISTERED: 'REGISTRATION.EMAIL_ALREADY_REGISTERED',
};

export const USER_ERROR = {
  USER_NOT_FOUND: 'USER.USER_NOT_FOUND',
};
