/**
 * User ROLES
 * */
export enum UserRole {
  USER = 'User',
  MOD = 'Mod',
  ADMIN = 'Admin',
}

export const REGISTRATION_ERROR = {
  VALIDATION_FAILED: 'REGISTRATION.VALIDATION_FAILED',
  PASSWORD_TOO_WEAK: 'REGISTRATION.PASSWORD_TOO_WEAK',
  EMAIL_ALREADY_REGISTERED: 'REGISTRATION.EMAIL_ALREADY_REGISTERED',
};

export const USER_ERROR = {
  USER_NOT_FOUND: 'USER.USER_NOT_FOUND',
  INVALID_EMAIL_OR_ID: 'USER.INVALID_EMAIL_OR_ID',
};
