/**
 * User ROLES
 * */
export enum UserRole {
  USER = 'User',
  MOD = 'Mod',
  ADMIN = 'Admin',
}

export enum USER_REGISTRATION_ERROR {
  VALIDATION_FAILED = 'USER_REGISTRATION.VALIDATION_FAILED',
  PASSWORD_TOO_WEAK = 'USER_REGISTRATION.PASSWORD_TOO_WEAK',
  EMAIL_ALREADY_REGISTERED = 'USER_REGISTRATION.EMAIL_ALREADY_REGISTERED',
}

export enum USER_ERROR {
  USER_NOT_FOUND = 'USER.USER_NOT_FOUND',
  INVALID_EMAIL_OR_ID = 'USER.INVALID_EMAIL_OR_ID',
}
