import { ConfigService } from '@nestjs/config';
import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import {
  DocumentBuilder,
  SwaggerCustomOptions,
  SwaggerModule,
} from '@nestjs/swagger';
import { Response } from 'express';
import expressRateLimit from 'express-rate-limit';
import helmet from 'helmet';
import { SpelunkerModule } from 'nestjs-spelunker';
import { AppModule } from './app.module';
import { Environment } from './config/env.variables';
import { ApiConfig } from './config/interfaces/api-config.interface';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);
  // app.enable('trust proxy'); // See: https://github.com/express-rate-limit/express-rate-limit/wiki/Troubleshooting-Proxy-Issues
  app.use(helmet());

  app.use(
    expressRateLimit({
      windowMs: 15 * 60 * 1000, // 15 minutes
      max: 100, // limit each IP to 100 requests per windowMs
      message: 'Too many requests from this IP, please try again later',
    }),
  );
  const createAccountLimiter = expressRateLimit({
    windowMs: 60 * 60 * 1000, // 1 hour window
    max: 3, // start blocking after 3 requests
    message: 'Too many accounts created from this IP, please try again later',
  });
  app.use('/auth/email/register', createAccountLimiter);

  if (process.env.NODE_ENV === Environment.Development) {
    setupDependencyGraph(app);
    setupOpenApiDocs(app);
  }

  const apiConfig = app.get<ConfigService>(ConfigService).get<ApiConfig>('api');

  await app.listen(apiConfig.internalPort);
}
bootstrap();

/**
 * Builds a Dependency Graph to provide a high level view of the NestJS application
 */
function setupDependencyGraph(app: NestExpressApplication) {
  // console.log(SpelunkerModule.explore(app));
  const commonModules = [
    'ConfigModule',
    'StandardResponseModule',
    'MongooseModule',
    'JwtModule',
  ];
  // 1. Generate the tree as text
  const tree = SpelunkerModule.explore(app);
  const root = SpelunkerModule.graph(tree);
  const edges = SpelunkerModule.findGraphEdges(root);
  const apiEndpointModuleIcon = 'fa:fa-globe ';
  const mermaidEdges = edges
    .filter(
      // filtering some modules out
      ({ from, to }) =>
        !(
          from.module.name === 'ConfigHostModule' ||
          to.module.name === 'ConfigHostModule' ||
          from.module.name === 'MongooseCoreModule' ||
          to.module.name === 'MongooseCoreModule' ||
          from.module.name === 'LoggerModule' ||
          to.module.name === 'LoggerModule'
        ),
    )
    .map(({ from, to }) => {
      const hasController = from.module.controllers.length > 0;
      const classTag = hasController ? ':::restEndpoint' : '';
      const iconTag = hasController ? apiEndpointModuleIcon : '';
      const shapeIn = hasController ? '{{' : '(';
      const shapeOut = hasController ? '}}' : ')';
      let lineStyle = '===>';
      if (
        from.module.name !== 'AppModule' &&
        !commonModules.includes(from.module.name) &&
        commonModules.includes(to.module.name)
      )
        lineStyle = '-.-';
      if (to.module.name === 'JwtModule' || from.module.name === 'JwtModule')
        lineStyle = '~~~';
      return `${from.module.name}${shapeIn}${iconTag}${from.module.name}${shapeOut}${classTag}${lineStyle}${to.module.name}`;
    });
  const header = `%%{ init: { 'flowchart': { 'curve': 'monotoneX' } } }%%
flowchart LR
  subgraph legend[ Legend ]
  subgraph legendPadding [ ]
    direction TB
    ex2(Module without routes)
    ex1{{fa:fa-globe Module exposing API endpoints}}:::restEndpoint
  end
  end
  subgraph appGraph[" "]
    direction LR
    subgraph CM[Common modules]
      ConfigModule
      StandardResponseModule
      MongooseModule
      JwtModule
    end
    subgraph MM[Main modules]
      UserModule
      AuthModule
      PoliciesModule
      MailerModule
    end`;
  const footer = `  end
classDef restEndpoint fill:darkgreen
classDef groupStyles rx:10,ry:10
class CM,MM groupStyles
classDef layoutGroup fill:none,stroke:none
class appGraph,legendPadding layoutGroup
style legend stroke-dasharray: 0 1 1,fill:none,opacity:0.75
`;
  const mermaidGraph = `${header}\n\t${mermaidEdges.join('\n\t')}\n${footer}`;
  app.getHttpAdapter().get('/dev-tools/graph.mmd', (req, res: Response) => {
    // res.set('Content-Type', 'text/markdown');
    res.set('Content-Type', 'text/vnd.mermaid');
    res.send(mermaidGraph);
    // Copy and paste in "https://mermaid.live/"
  });
}

/**
 * Builds the OpenAPI JSON object providing documentation for the app
 */
function setupOpenApiDocs(app: NestExpressApplication) {
  // app.useStaticAssets(join(__dirname, '../..', 'docs'), { prefix: '/docs' });
  const config = new DocumentBuilder()
    .setTitle('API Live Documentation')
    .setDescription(
      'Auto generated by @nestjs/swagger following the Open API specification.',
    )
    .setVersion('1.0')
    .addBearerAuth()
    .build();

  const swaggerUiOptions: SwaggerCustomOptions = {
    // explorer: true,
    swaggerOptions: {
      filter: true,
      // deepLinking: true,
      persistAuthorization: true,
      defaultModelsExpandDepth: 0, // set to -1 to hide the 'Schemas' section from docs
    },
  };
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('docs', app, document, swaggerUiOptions);
}
