export const EMOJIS = {
  HEART: `❤️`,
  COFFEE: `☕️`,
  BEER: `🍺`,
  BROKEN_HEART: `💔`,
  CRYING: `😿`,
  HEART_EYES: `😻`,
  JOY: `😺`,
  KISSING: `😽`,
  SCREAM: `🙀`,
  ROCKET: `🚀`,
  SMIRK: `😼`,
  RAISED_HANDS: `🙌`,
  POINT_RIGHT: `👉`,
  ZAP: `⚡️`,
  BOOM: `💥`,
  PRAY: `🙏`,
  WINE: `🍷`,
};
