export enum AUTH_ERROR {
  EMAIL_SYNTAX_ERROR = 'AUTH.EMAIL_SYNTAX_ERROR',
}

export enum LOGIN_ERROR {
  EMAIL_NOT_FOUND = 'LOGIN.UNAUTHORIZED',
  INVALID_PASSWORD = 'LOGIN.UNAUTHORIZED',
  EMAIL_NOT_VERIFIED = 'LOGIN.EMAIL_NOT_VERIFIED',
}

export enum LOGIN_SUCCESS {
  SUCCESS = 'LOGIN.SUCCESS',
  AUTO_SWITCH = 'LOGIN.SUCCESS.AUTO_SWITCH',
}

export enum REGISTRATION_SUCCESS {
  SUCCESS = 'REGISTRATION.SUCCESS',
  AUTO_LOGIN = 'REGISTRATION.SUCCESS.AUTO_LOGIN',
  VERIFY_EMAIL_TO_PROCEED = 'REGISTRATION.SUCCESS.VERIFY_EMAIL_TO_PROCEED',
}

export enum EMAIL_VERIFICATION_ERROR {
  EMAIL_SENT_RECENTLY = 'EMAIL_VERIFICATION.EMAIL_SENT_RECENTLY',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_VERIFICATION.EMAIL_ALREADY_VERIFIED',
  USER_NOT_FOUND = 'EMAIL_VERIFICATION.USER_NOT_FOUND',
  TOKEN_NOT_FOUND = 'EMAIL_VERIFICATION.TOKEN_NOT_FOUND',
  TOKEN_NOT_CREATED = 'EMAIL_VERIFICATION.TOKEN_NOT_CREATED',
  EMAIL_NOT_SENT = 'EMAIL_VERIFICATION.EMAIL_NOT_SENT',
}

export enum EMAIL_VERIFICATION_SUCCESS {
  SUCCESS = 'EMAIL_VERIFICATION.SUCCESS',
  EMAIL_RESENT = 'EMAIL_VERIFICATION.EMAIL_RESENT',
}

export enum FORGOT_PASSWORD_ERROR {
  EMAIL_SENT_RECENTLY = 'FORGOT_PASSWORD.EMAIL_SENT_RECENTLY',
  USER_NOT_FOUND = 'FORGOT_PASSWORD.USER_NOT_FOUND',
  TOKEN_NOT_CREATED = 'FORGOT_PASSWORD.TOKEN_NOT_CREATED',
  EMAIL_NOT_SENT = 'FORGOT_PASSWORD.EMAIL_NOT_SENT',
}

export enum FORGOT_PASSWORD_SUCCESS {
  EMAIL_SENT = 'FORGOT_PASSWORD.EMAIL_SENT',
}

export enum RESET_PASSWORD_ERROR {
  USER_NOT_FOUND = 'RESET_PASSWORD.USER_NOT_FOUND',
  UNAUTHORIZED = 'RESET_PASSWORD.UNAUTHORIZED',
  REQUEST_NOT_FOUND = 'RESET_PASSWORD.REQUEST_NOT_FOUND',
  LINK_EXPIRED = 'RESET_PASSWORD.LINK_EXPIRED',
}

export enum RESET_PASSWORD_SUCCESS {
  SUCCESS = 'RESET_PASSWORD.SUCCESS',
}
